[phases.setup]
nixPkgs = ["nodejs-18_x", "pnpm", "go_1_24", "git", "ca-certificates"]

[phases.build]
cmds = [
  # Build frontend
  "cd frontend && pnpm install && pnpm run build",
  # Build backend, embedding frontend assets
  "cd backend && go mod download",
  "cp -r frontend/dist backend/cmd/app/dist",  # Copy frontend build into backend
  "cd backend && CGO_ENABLED=0 go build -o app ./cmd/app/main.go"
]

[start]
cmd = "cd backend && ./app"
