name: Build and Test

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/build-and-test.yml'
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          go-version: 1.24

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
